[project]
name = "red-black-tree"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "AllenWu233", email = "allenwu233@163.com"},
]
dependencies = []
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
